version: '3.8'

services:
  webd:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 1361:5000
    env_file:
      - ./.env.dev
    depends_on:
      - dbd
  dbd:
    build: ./services/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - PGUSER=hello_flask
    ports:
      - 1457:5432

volumes:
  postgres_data:
