name: tests
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      run: |
        pip3 install -r requirements.txt
    - name: docker
      run: |
        git submodule init
        git submodule update
        docker-compose up -d --build
        docker ps -a
        sleep 20
        python3 fake_data_urls.py
        python3 fake_data_users.py
        python3 fake_data_tweets.py
